### ISSUE TITLE
Multiple exceptions under Linux

### ISSUE THREAD

**Issue by davidrupprecht** [proj3rd/tool3rd#20]
Dear all,

this is a very nice tool. Thanks. I got in running under Linux using yarn. Unfortunately, when trying to download the specs from the cloud multiple exceptions are not caught. See the screenshots below. Thanks  

![image](https://user-images.githubusercontent.com/18260006/115963802-40869e00-a521-11eb-9b22-15446456f854.png)
![image](https://user-images.githubusercontent.com/18260006/115963817-5c8a3f80-a521-11eb-95b1-24b071d1a0dc.png)

**Comment by sjeon87** [comment]
Dear @davidrupprecht, I've just uploaded Linux binaries. Could you check if https://github.com/proj3rd/tool3rd/releases/tag/v1.8.0 works? I've tested it on Ubuntu 20.04 LTS 64-bit running in VirtualBox. If you have any trouble, please let me know.

**Comment by davidrupprecht** [comment]
Hi @gsongsong,

thanks that work. Looks like my build chain is buggy or something. 

Best regards,
David
