### ISSUE TITLE
v1.9.1-alpha doesn't work on asn1 file 

### ISSUE THREAD

**Issue by gmg2719** [proj3rd/tool3rd#22]
when try to load asn1 file, the tool stuck forever.

**Comment by sjeon87** [comment]
Thanks for registering issue.
Could you tell me which file did you try to load?

**Comment by sjeon87** [comment]
Seems a problem causing the issue found. Will upload new version after somet tests.

**Comment by sjeon87** [comment]
Please check out v1.9.2-alpha

**Comment by gmg2719** [comment]
Thanks, it fixed. works well!
